config/routes.rb
Rails.application.routes.draw do
  root to: 'person_sessions#new'
  resources :students
  resources :teachers
  resources :deans
  resources :classrooms
  resources :branches, expect: [:show]
  resources :lessons
  resources :exams
  resources :semesters, expect: [:show]
  resources :notes, only: [:create]
  resources :person_sessions, only: [:new, :create, :edit, :update]
  delete 'logout', controller: :person_sessions, action: :destroy
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(person)
    person ||= Person.new  # Assume une personne non connectée par défaut
    case person.type
    when 'Dean'
      can :manage, [Classroom, Person, Semester, Note, Exam, Lesson, Branch]
    when 'Teacher'
      can :read, Lesson, teacher_id: person.id
      can :manage, Exam, lesson: { teacher_id: person.id }
      can :manage, Note, exam: { lesson: { teacher_id: person.id } }
    when 'Student'
      can :read, Student, id: person.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/branch.rb
class Branch < ApplicationRecord
  def self.active
    where('archived = ?', 0)
  end
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :teacher
  has_many :classrooms_students
  has_many :lessons
  has_many :semesters, through: :lessons
  has_many :students, through: :classrooms_students

  def self.active
    current_year = Date.today.year
    where "end_at >= ?", current_year
  end

  def unique_semesters
    semesters.distinct
  end
end

app/models/classrooms_student.rb
class ClassroomsStudent < ApplicationRecord
  belongs_to :classroom
  belongs_to :student

end

app/models/dean.rb
class Dean < Teacher
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :lesson
  has_many :students, through: :lesson
  has_many :notes

  validates :name, presence: true
  validates :date, presence: true
  validates :weight, presence: true, numericality: { greater_than: 0 }

  def note_for_student student
    notes.find_by student: student
  end

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :classroom
  belongs_to :teacher
  belongs_to :branch
  belongs_to :semester
  has_many :exams
  has_many :students, through: :classroom

  def self.active
    Lesson.joins([:classroom, :branch]).merge(Classroom.active).merge(Branch.active)
  end

  def average_for_student student
    total_weight = 0
    weighted_sum = 0.0
    exams.each do |exam|
      weight = exam.weight || 1
      weighted_sum += (exam.note_for_student(student)&.value || 1.0) * weight
      total_weight += weight
    end
    weighted_sum / (total_weight === 0 ? 1 : total_weight)
  end

end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :exam
  belongs_to :student
end

app/models/person.rb
class Person < ApplicationRecord
  has_secure_password
  before_save :downcase_email
  validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, presence: true, uniqueness: true

  def full_name
    first_name + " " + last_name
  end

  def is_teacher?
    type == 'Teacher'
  end

  def is_student?
    type == 'Student'
  end

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/models/semester.rb
class Semester < ApplicationRecord
  has_many :lessons

  def self.active
    where('year >= ?', Date.today.year)
  end

  def name
    year.to_s + " - " + number.to_s
  end

  def average_for_student student
    lessons_with_exams = lessons.active.select { |lesson| lesson.exams.exists? }

    return 0 if lessons_with_exams.empty?

    average_sum = lessons_with_exams.sum { |lesson| lesson.average_for_student(student) }

    average_sum / lessons_with_exams.length.to_f
  end
end

app/models/student.rb
class Student < Person
  has_many :classrooms_students
  has_many :classrooms, through: :classrooms_students
  has_many :lessons, through: :classrooms
  has_many :semesters, through: :lessons

  def current_classroom
    classrooms.where('end_at >= ?', Date.today.year).order(start_at: :asc).first
  end
end

app/models/teacher.rb
class Teacher < Person
  has_many :classrooms
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  load_and_authorize_resource
  def index
    @students = Student.all
  end

  def show
    @student = Student.find params[:id]
  end

  def new
    @student = Student.new

  end

  def create
    @student = Student.new student_params

    if @student.save
      flash[:success] = "Student created successfully"
      redirect_to @student
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])

    if @student.update(student_params)
      flash[:success] = "Student updated successfully"
      redirect_to @student
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    flash[:success] = "Student deleted successfully"
    redirect_to students_path
  end

  private

  def student_params
    params.require(:student).permit(:first_name, :last_name, :email,:password, :city, :npa, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for_flash(flash_type)
    case flash_type.to_sym
    when :success
      "alert-success"
    when :error
      "alert-danger"
    when :alert
      "alert-warning"
    when :notice
      "alert-info"
    else
      flash_type.to_s
    end
  end
end

app/helpers/branch_helper.rb
module BranchHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/students/_form.html.erb
<%= form_with model: @student do | form | %>
    <div>
        <%= form.label :first_name, class: "form-label" %>
        <%= form.text_field :first_name, class: "form-control" %>
    </div>
    <div class="mt-2">
        <%= form.label :last_name, class: "form-label" %>
        <%= form.text_field :last_name, class: "form-control" %>
    </div>
    <div class="mt-2">
        <%= form.label :email, class: "form-label" %>
        <%= form.email_field :email, class: "form-control" %>
    </div>
    <div class="mt-2">
        <%= form.label :password, class: "form-label" %>
        <%= form.password_field :password, class: "form-control" %>
    </div>
    <div class="mt-2">
        <%= form.label :address, class: "form-label" %>
        <%= form.text_field :address, class: "form-control" %>
    </div>
    <div class="mt-2">
        <%= form.label :npa, class: "form-label" %>
        <%= form.number_field :npa, class: "form-control" %>
    </div>
    <div class="mt-2">
        <%= form.label :city, class: "form-label" %>
        <%= form.text_field :city, class: "form-control" %>
    </div>
    <%= form.submit class: "btn btn-primary mt-2" %>
<% end %>

app/views/students/edit.html.erb
<h1>Update Student </h1>
<%= render "students/form" %>

app/views/students/index.html.erb
<h1>Students</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Options</th>
        </tr>
    </thead>
    <tbody>
        <% @students.each do |student| %>
            <tr>
                <td><%= student.id %></td>
                <td><%= student.first_name %></td>
                <td><%= student.last_name %></td>
                <td>
                    <a href="<%= edit_student_path student %>" class="btn btn-warning ml-2">Edit</a>
                    <a href="<%= student_path student %>" class="btn btn-primary mr-2">See</a>
                    <%= link_to 'Delete', student_path(student.id), data: { "turbo-method": :delete, "turbo-confirm": "Are you sure ?" }, class: "btn btn-danger" %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>
<a href="<%= new_student_path %>" class="btn btn-primary">New</a>

app/views/students/new.html.erb
<h1>Create new student</h1>
<%= render "students/form" %>

app/views/students/show.html.erb
<div class="container mt-4">
  <h1 class="mb-3"><%= @student.first_name %> <%= @student.last_name %></h1>
  <h2 class="mb-3">My notes</h2>
  <p class="mb-3">Classroom : <%= @student.current_classroom&.name %></p>
  <% @student.current_classroom&.unique_semesters&.each do |semester| %>
    <div class="card mb-3">
      <div class="card-header" style="display:flex; justify-content: space-between; align-items: center">
        <div>
          Semester <%= semester.name %>
        </div>
        <div>
          <strong>Average : <%= semester.average_for_student @student %></strong>
        </div>
      </div>
      <div class="card-body">
        <% semester.lessons.active.each do |lesson| %>
          <h5 class="card-title"><%= lesson.branch.name %></h5>
          <% lesson.exams.each do |exam| %>
            <p class="card-text"><strong><%= exam.name %> (<%= exam.date %>): </strong> <%= exam.note_for_student(@student)&.value %></p>
          <% end %>
          <p class="card-text"><strong>Average: <%= lesson.average_for_student(@student) %></strong></p>
        <% end %>
      </div>
    </div>
  <% end %>
</div>