config/routes.rb
Rails.application.routes.draw do
  root to: 'person_sessions#new'
  resources :students
  resources :teachers
  resources :deans
  resources :classrooms
  resources :branches, expect: [:show]
  resources :lessons
  resources :exams
  resources :semesters, expect: [:show]
  resources :notes, only: [:create]
  resources :person_sessions, only: [:new, :create, :edit, :update]
  delete 'logout', controller: :person_sessions, action: :destroy
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(person)
    person ||= Person.new  # Assume une personne non connectée par défaut
    case person.type
    when 'Dean'
      can :manage, [Classroom, Person, Semester, Note, Exam, Lesson, Branch]
    when 'Teacher'
      can :read, Lesson, teacher_id: person.id
      can :manage, Exam, lesson: { teacher_id: person.id }
      can :manage, Note, exam: { lesson: { teacher_id: person.id } }
    when 'Student'
      can :read, Student, id: person.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/branch.rb
class Branch < ApplicationRecord
  def self.active
    where('archived = ?', 0)
  end
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :teacher
  has_many :classrooms_students
  has_many :lessons
  has_many :semesters, through: :lessons
  has_many :students, through: :classrooms_students

  def self.active
    current_year = Date.today.year
    where "end_at >= ?", current_year
  end

  def unique_semesters
    semesters.distinct
  end
end

app/models/classrooms_student.rb
class ClassroomsStudent < ApplicationRecord
  belongs_to :classroom
  belongs_to :student

end

app/models/dean.rb
class Dean < Teacher
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :lesson
  has_many :students, through: :lesson
  has_many :notes

  validates :name, presence: true
  validates :date, presence: true
  validates :weight, presence: true, numericality: { greater_than: 0 }

  def note_for_student student
    notes.find_by student: student
  end

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :classroom
  belongs_to :teacher
  belongs_to :branch
  belongs_to :semester
  has_many :exams
  has_many :students, through: :classroom

  def self.active
    Lesson.joins([:classroom, :branch]).merge(Classroom.active).merge(Branch.active)
  end

  def average_for_student student
    total_weight = 0
    weighted_sum = 0.0
    exams.each do |exam|
      weight = exam.weight || 1
      weighted_sum += (exam.note_for_student(student)&.value || 1.0) * weight
      total_weight += weight
    end
    weighted_sum / (total_weight === 0 ? 1 : total_weight)
  end

end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :exam
  belongs_to :student
end

app/models/person.rb
class Person < ApplicationRecord
  has_secure_password
  before_save :downcase_email
  validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, presence: true, uniqueness: true

  def full_name
    first_name + " " + last_name
  end

  def is_teacher?
    type == 'Teacher'
  end

  def is_student?
    type == 'Student'
  end

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/models/semester.rb
class Semester < ApplicationRecord
  has_many :lessons

  def self.active
    where('year >= ?', Date.today.year)
  end

  def name
    year.to_s + " - " + number.to_s
  end

  def average_for_student student
    lessons_with_exams = lessons.active.select { |lesson| lesson.exams.exists? }

    return 0 if lessons_with_exams.empty?

    average_sum = lessons_with_exams.sum { |lesson| lesson.average_for_student(student) }

    average_sum / lessons_with_exams.length.to_f
  end
end

app/models/student.rb
class Student < Person
  has_many :classrooms_students
  has_many :classrooms, through: :classrooms_students
  has_many :lessons, through: :classrooms
  has_many :semesters, through: :lessons

  def current_classroom
    classrooms.where('end_at >= ?', Date.today.year).order(start_at: :asc).first
  end
end

app/models/teacher.rb
class Teacher < Person
  has_many :classrooms
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  load_and_authorize_resource
  def index
    @lessons = Lesson.includes([:branch, :teacher, :classroom, :semester])
    if current_user.type == 'Teacher'
      @lessons = @lessons.active.where('lessons.teacher_id = ?', current_user.id)
    elsif params[:filter] == 'all'
      @lessons = @lessons.all
    else
      @lessons = @lessons.active
    end
  end

  def show
    @lesson = Lesson.find params[:id]
    @exam = Exam.new
    @note = Note.new
    @note.exam = @exam
    @exam.lesson = @lesson
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new lesson_params

    if @lesson.save
      flash[:success] = "Lesson created successfully"
      redirect_to @lesson
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @lesson = Lesson.find(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:id])

    if @lesson.update(lesson_params)
      flash[:success] = "Lesson updated successfully"
      redirect_to @lesson
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    flash[:success] = "Lesson deleted successfully"
    redirect_to lessons_path
  end

  private

  def lesson_params
    params.require(:lesson).permit(:semester_id, :teacher_id, :branch_id, :classroom_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for_flash(flash_type)
    case flash_type.to_sym
    when :success
      "alert-success"
    when :error
      "alert-danger"
    when :alert
      "alert-warning"
    when :notice
      "alert-info"
    else
      flash_type.to_s
    end
  end
end

app/helpers/branch_helper.rb
module BranchHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/lessons/_exam_form.html.erb
<% if @exam.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Fix the following errors:</h4>
    <ul>
      <% @exam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @exam do |form| %>
  <td>
    <%= form.text_field :name, class: "form-control" %>
  </td>
  <td>
    <%= form.text_field :weight, value: 1, class: "form-control" %>
  </td>
  <td>
    <%= form.date_field :date, value: Date.today, class: "form-control" %>
  </td>
  <td>
    <%= form.hidden_field :lesson_id, class: "form-control" %>
    <%= form.submit "Submit", class: "btn btn-primary mt-2" %>
  </td>
<% end %>

app/views/lessons/_form.html.erb
<%= form_with model: @lesson do | form | %>
    <div class="mt-2">
        <%= form.label :branch_id, class: "form-label" %>
        <%= form.collection_select(:branch_id, Branch.active, :id, :name, {}, {class: "form-control"}) %>
    </div>
        <div class="mt-2">
        <%= form.label :classroom_id, class: "form-label" %>
        <%= form.collection_select(:classroom_id, Classroom.active, :id, :name, {}, {class: "form-control"}) %>
    </div>
    <div class="mt-2">
        <%= form.label :teacher_id, class: "form-label" %>
        <%= form.collection_select(:teacher_id, Teacher.all, :id, :full_name, {}, {class: "form-control"}) %>
    </div>
        <div class="mt-2">
        <%= form.label :semester_id, class: "form-label" %>
        <%= form.collection_select(:semester_id, Semester.active, :id, :name, {}, {class: "form-control"}) %>
    </div>
    <%= form.submit class: "btn btn-primary mt-2" %>
<% end %>

app/views/lessons/edit.html.erb
<h1>Update lesson </h1>
<%= render "lessons/form" %>

app/views/lessons/index.html.erb
<h1>Lessons</h1>
<% if can? :manage, Lesson %>
  <%= form_with(url: lessons_path, method: :get, local: true) do %>
    <div style="max-width: 175px; display:flex; justify-content: center; align-items: center; gap: 1rem;">
      <label for="filter">Filter:</label>
      <%=
        select_tag(
          :filter,
          options_for_select([['Active', 'active'],['All', 'all']], params[:filter] || 'Active'),
          onchange: 'this.form.submit();',
          class: 'form-control',
        )
      %>
    </div>
  <% end %>
<% end %>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Classroom</th>
            <th scope="col">Branch</th>
            <th scope="col">Teacher</th>
            <th scope="col">Semester</th>
            <th scope="col">Options</th>
        </tr>
    </thead>
    <tbody>
        <% @lessons.each do |lesson| %>
            <tr>
                <td><%= lesson.id %></td>
                <td><%= lesson.classroom&.name %></td>
                <td><%= lesson.branch&.name %></td>
                <td><%= lesson.teacher&.full_name %></td>
                <td><%= lesson.semester&.name %></td>
                <td>
                  <% if can? :manage, Lesson %>
                    <a href="<%= edit_lesson_path lesson %>" class="btn btn-warning ml-2">Edit</a>
                    <%= link_to 'Delete', lesson_path(lesson.id), data: { "turbo-method": :delete, "turbo-confirm": "Are you sure ?" }, class: "btn btn-danger" %>
                  <% end %>
                    <a href="<%= lesson_path lesson %>" class="btn btn-primary mr-2">See</a>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>
<% if can? :manage, Lesson %>
<a href="<%= new_lesson_path %>" class="btn btn-primary">New</a>
<% end %>

app/views/lessons/new.html.erb
<h1>Create new lesson</h1>
<%= render "lessons/form" %>

app/views/lessons/show.html.erb
<h1>Lesson <%= @lesson.branch.name %></h1>
<h2>Exams</h2>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Weight</th>
            <th scope="col">Date</th>
            <th scope="col">Options</th>
        </tr>
    </thead>
    <tbody>
        <% @lesson.exams.each do |exam| %>
            <tr>
                <td><%= exam.name %></td>
                <td><%= exam.weight %></td>
                <td><%= exam.date %></td>
                <td>
                    <a href="<%= exam_path exam %>" class="btn btn-primary mr-2">See</a>
                    <%= link_to 'Delete', exam_path(exam.id), data: { "turbo-method": :delete, "turbo-confirm": "Are you sure ?" }, class: "btn btn-danger" %>
                </td>
            </tr>
        <% end %>
        <tr>
            <%= render "lessons/exam_form" %>
        </tr>
    </tbody>
</table>