config/routes.rb
Rails.application.routes.draw do
  root to: 'person_sessions#new'
  resources :students
  resources :teachers
  resources :deans
  resources :classrooms
  resources :branches, expect: [:show]
  resources :lessons
  resources :exams
  resources :semesters, expect: [:show]
  resources :notes, only: [:create]
  resources :person_sessions, only: [:new, :create, :edit, :update]
  delete 'logout', controller: :person_sessions, action: :destroy
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(person)
    person ||= Person.new  # Assume une personne non connectée par défaut
    case person.type
    when 'Dean'
      can :manage, [Classroom, Person, Semester, Note, Exam, Lesson, Branch]
    when 'Teacher'
      can :read, Lesson, teacher_id: person.id
      can :manage, Exam, lesson: { teacher_id: person.id }
      can :manage, Note, exam: { lesson: { teacher_id: person.id } }
    when 'Student'
      can :read, Student, id: person.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/branch.rb
class Branch < ApplicationRecord
  def self.active
    where('archived = ?', 0)
  end
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :teacher
  has_many :classrooms_students
  has_many :lessons
  has_many :semesters, through: :lessons
  has_many :students, through: :classrooms_students

  def self.active
    current_year = Date.today.year
    where "end_at >= ?", current_year
  end

  def unique_semesters
    semesters.distinct
  end
end

app/models/classrooms_student.rb
class ClassroomsStudent < ApplicationRecord
  belongs_to :classroom
  belongs_to :student

end

app/models/dean.rb
class Dean < Teacher
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :lesson
  has_many :students, through: :lesson
  has_many :notes

  validates :name, presence: true
  validates :date, presence: true
  validates :weight, presence: true, numericality: { greater_than: 0 }

  def note_for_student student
    notes.find_by student: student
  end

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :classroom
  belongs_to :teacher
  belongs_to :branch
  belongs_to :semester
  has_many :exams
  has_many :students, through: :classroom

  def self.active
    Lesson.joins([:classroom, :branch]).merge(Classroom.active).merge(Branch.active)
  end

  def average_for_student student
    total_weight = 0
    weighted_sum = 0.0
    exams.each do |exam|
      weight = exam.weight || 1
      weighted_sum += (exam.note_for_student(student)&.value || 1.0) * weight
      total_weight += weight
    end
    weighted_sum / (total_weight === 0 ? 1 : total_weight)
  end

end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :exam
  belongs_to :student
end

app/models/person.rb
class Person < ApplicationRecord
  has_secure_password
  before_save :downcase_email
  validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, presence: true, uniqueness: true

  def full_name
    first_name + " " + last_name
  end

  def is_teacher?
    type == 'Teacher'
  end

  def is_student?
    type == 'Student'
  end

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/models/semester.rb
class Semester < ApplicationRecord
  has_many :lessons

  def self.active
    where('year >= ?', Date.today.year)
  end

  def name
    year.to_s + " - " + number.to_s
  end

  def average_for_student student
    lessons_with_exams = lessons.active.select { |lesson| lesson.exams.exists? }

    return 0 if lessons_with_exams.empty?

    average_sum = lessons_with_exams.sum { |lesson| lesson.average_for_student(student) }

    average_sum / lessons_with_exams.length.to_f
  end
end

app/models/student.rb
class Student < Person
  has_many :classrooms_students
  has_many :classrooms, through: :classrooms_students
  has_many :lessons, through: :classrooms
  has_many :semesters, through: :lessons

  def current_classroom
    classrooms.where('end_at >= ?', Date.today.year).order(start_at: :asc).first
  end
end

app/models/teacher.rb
class Teacher < Person
  has_many :classrooms
end

app/controllers/deans_controller.rb
class DeansController < ApplicationController
  load_and_authorize_resource
  def index
    @deans = Dean.all
  end

  def show
    @dean = Dean.find params[:id]
  end

  def new
    @dean = Dean.new
  end

  def create
    puts dean_params
    @dean = Dean.new dean_params

    if @dean.save
      flash[:success] = "Dean created successfully"
      redirect_to deans_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @dean = Dean.find(params[:id])
  end

  def update
    @dean = Dean.find(params[:id])

    if @dean.update(dean_params)
      flash[:success] = "Dean updated successfully"
      redirect_to @dean
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @dean = Dean.find(params[:id])
    @dean.destroy
    flash[:success] = "Dean deleted successfully"
    redirect_to deans_path
  end

  private

  def dean_params
    params.require(:dean).permit(:first_name,:password, :last_name, :email, :city, :npa, :address, :role)
  end
end

app/helpers/branch_helper.rb
module BranchHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/deans/_form.html.erb
<%= form_with model: @dean do | form | %>
    <div>
        <%= form.label :first_name, class: "form-label" %>
        <%= form.text_field :first_name, class: "form-control" %>
    </div>
    <div class="mt-2">
        <%= form.label :last_name, class: "form-label" %>
        <%= form.text_field :last_name, class: "form-control" %>
    </div>
    <div class="mt-2">
        <%= form.label :email, class: "form-label" %>
        <%= form.email_field :email, class: "form-control" %>
    </div>
    <div class="mt-2">
        <%= form.label :password, class: "form-label" %>
        <%= form.password_field :password, class: "form-control" %>
    </div>
    <div class="mt-2">
        <%= form.label :address, class: "form-label" %>
        <%= form.text_field :address, class: "form-control" %>
    </div>
    <div class="mt-2">
        <%= form.label :npa, class: "form-label" %>
        <%= form.number_field :npa, class: "form-control" %>
    </div>
    <div class="mt-2">
        <%= form.label :city, class: "form-label" %>
        <%= form.text_field :city, class: "form-control" %>
    </div>
    <%= form.submit class: "btn btn-primary mt-2" %>
<% end %>

app/views/deans/edit.html.erb
<h1>Update dean </h1>
<%= render "deans/form" %>

app/views/deans/index.html.erb
<h1>Deans</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Options</th>
        </tr>
    </thead>
    <tbody>
        <% @deans.each do |dean| %>
            <tr>
                <td><%= dean.id %></td>
                <td><%= dean.first_name %></td>
                <td><%= dean.last_name %></td>
                <td>
                    <a href="<%= edit_dean_path dean %>" class="btn btn-warning ml-2">Edit</a>
                    <a href="<%= dean_path dean %>" class="btn btn-primary mr-2">See</a>
                    <%= link_to 'Delete', dean_path(dean.id), data: { "turbo-method": :delete, "turbo-confirm": "Are you sure ?" }, class: "btn btn-danger" %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>
<a href="<%= new_dean_path %>" class="btn btn-primary">New</a>

app/views/deans/new.html.erb
<h1>Create new dean</h1>
<%= render "deans/form" %>

app/views/deans/show.html.erb
<h1><%= @dean.first_name %> <%= @dean.last_name %></h1>