config/routes.rb
Rails.application.routes.draw do
  root to: 'person_sessions#new'
  resources :students
  resources :teachers
  resources :deans
  resources :classrooms
  resources :branches, expect: [:show]
  resources :lessons
  resources :exams
  resources :semesters, expect: [:show]
  resources :notes, only: [:create]
  resources :person_sessions, only: [:new, :create, :edit, :update]
  delete 'logout', controller: :person_sessions, action: :destroy
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(person)
    person ||= Person.new  # Assume une personne non connectée par défaut
    case person.type
    when 'Dean'
      can :manage, [Classroom, Person, Semester, Note, Exam, Lesson, Branch]
    when 'Teacher'
      can :read, Lesson, teacher_id: person.id
      can :manage, Exam, lesson: { teacher_id: person.id }
      can :manage, Note, exam: { lesson: { teacher_id: person.id } }
    when 'Student'
      can :read, Student, id: person.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/branch.rb
class Branch < ApplicationRecord
  def self.active
    where('archived = ?', 0)
  end
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :teacher
  has_many :classrooms_students
  has_many :lessons
  has_many :semesters, through: :lessons
  has_many :students, through: :classrooms_students

  def self.active
    current_year = Date.today.year
    where "end_at >= ?", current_year
  end

  def unique_semesters
    semesters.distinct
  end
end

app/models/dean.rb
class Dean < Teacher
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :lesson
  has_many :students, through: :lesson
  has_many :notes

  validates :name, presence: true
  validates :date, presence: true
  validates :weight, presence: true, numericality: { greater_than: 0 }

  def note_for_student student
    notes.find_by student: student
  end

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :classroom
  belongs_to :teacher
  belongs_to :branch
  belongs_to :semester
  has_many :exams
  has_many :students, through: :classroom

  def self.active
    Lesson.joins([:classroom, :branch]).merge(Classroom.active).merge(Branch.active)
  end

  def average_for_student student
    total_weight = 0
    weighted_sum = 0.0
    exams.each do |exam|
      weight = exam.weight || 1
      weighted_sum += (exam.note_for_student(student)&.value || 1.0) * weight
      total_weight += weight
    end
    weighted_sum / (total_weight === 0 ? 1 : total_weight)
  end

end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :exam
  belongs_to :student
end

app/models/person.rb
class Person < ApplicationRecord
  has_secure_password
  before_save :downcase_email
  validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, presence: true, uniqueness: true

  def full_name
    first_name + " " + last_name
  end

  def is_teacher?
    type == 'Teacher'
  end

  def is_student?
    type == 'Student'
  end

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/models/semester.rb
class Semester < ApplicationRecord
  has_many :lessons

  def self.active
    where('year >= ?', Date.today.year)
  end

  def name
    year.to_s + " - " + number.to_s
  end

  def average_for_student student
    lessons_with_exams = lessons.active.select { |lesson| lesson.exams.exists? }

    return 0 if lessons_with_exams.empty?

    average_sum = lessons_with_exams.sum { |lesson| lesson.average_for_student(student) }

    average_sum / lessons_with_exams.length.to_f
  end
end

app/models/student.rb
class Student < Person
  has_many :classrooms_students
  has_many :classrooms, through: :classrooms_students
  has_many :lessons, through: :classrooms
  has_many :semesters, through: :lessons

  def current_classroom
    classrooms.where('end_at >= ?', Date.today.year).order(start_at: :asc).first
  end
end

app/models/teacher.rb
class Teacher < Person
  has_many :classrooms
end

app/helpers/branch_helper.rb
module BranchHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gesteleves</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Gesteleves</a>
          <% if current_user %>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <% if can? :manage, Student %>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="<%= students_url %>">Students</a>
                </li>
                <% end %>
                <% if can? :manage, Teacher %>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="<%= teachers_url %>">Teachers</a>
                </li>
                <% end %>
                <% if can? :manage, Dean %>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="<%= deans_url %>">Deans</a>
                </li>
                <% end %>
                <% if can? :manage, Classroom %>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="<%= classrooms_url %>">Classrooms</a>
                </li>
                <% end %>
                <% if can? :manage, Branch %>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="<%= branches_url %>">Branches</a>
                </li>
                <% end %>
                <% if can? :manage, Semester %>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="<%= semesters_url %>">Semesters</a>
                </li>
                <% end %>
                <% if can? :manage, Lesson %>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="<%= lessons_url %>">Lessons</a>
                </li>
                <% end %>
              </ul>
            </div>
            <div>
              <%= link_to 'Log out', logout_path, data: { "turbo-method": :delete } %>
            </div>
          <% end %>
        </div>
      </nav>
    </header>
    <main class="container">
      <% flash.each do |type, message| %>
        <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissible fade show" role="alert">
          <%= message %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>